services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
      MYSQL_DB: minimalapi
    depends_on:
      - db
  db:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: minimalapi

volumes:
  todo-mysql-data:

